name: Process Submiteed Setup Form  

on:
  issues:
    types:
      - opened

jobs:
  process-vars:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT }}
    #if: ${{ contains(github.event.*.labels.*.name, 'init') }}
    if: ${{ contains(github.event.issue.title, '[Setup New Company]') }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract Issue Details
        run: |
          echo "${{ github.event.issue.body }}" | base64 -w0 > ./B64
          cat ./B64 | base64 -d | sed '/^[[:space:]]*$/d' > ./OUTPUT
          VAR_NAMES=$(cat ./OUTPUT | grep \#\#\# | awk '{print $2}')
          for VARIABLE in ${VAR_NAMES}
          do
            VALUE=$(cat OUTPUT | grep -A1 ${VARIABLE}| tail -n1 | grep -v \#)
            gh variable set $VARIABLE --body "${VALUE}"
          done

      - name: cleanup
        run: | 
          rm ./B64
          rm ./OUTPUT
          mv .github/workflows/process_setup_issue.yml .github/workflows/process_setup_issue_done
                
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.PAT }}
          add_timestamp: true
          commit-message: 'New Setup Complete'
          title: '[Setup Complete]'
          body: >
            Updates to files to be applied
          labels: setup_done
          branch: setup_done
