# This is a basic workflow to help you get started with Actions

name: init

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          cp src/init.sh ./init.sh
          chmod +x init.sh
          ./init.sh 

      - name: cleanup files
        run: |
          rm ./init.sh
          mv .github/workflows/init.yml .github/workflows/init_completed
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.PAT }}
          add_timestamp: true
          commit-message: 'New Setup Merge'
          title: '[Setup New Company]'
          body: >
            Updates to files to be applied
          labels: initial_setup
          branch: initial_setup
